x-airflow-common:
  &airflow-common
  build: .
  image: airflow:latest
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
  env_file:
    - .env

services:
  redis:
    image: redis:7.4.1-alpine3.20
    container_name: redis
    environment:
      - TZ=America/Chicago
    networks:
      - airflow
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping | grep PONG
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s

  postgres:
    image: postgres:17.3-alpine3.21
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    restart: always
    container_name: postgres
    networks:
      - airflow


  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    restart: always
    container_name: airflow-webserver
    depends_on:
      - airflow-scheduler
    networks:
      - airflow

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    ports:
      - "8974:8974"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8974/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    restart: always
    container_name: airflow-scheduler
    depends_on:
      - airflow-init
    networks:
      - airflow

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      _AIRFLOW_DB_MIGRATE: 'true'
    depends_on:
      - postgres
      - redis
    networks:
      - airflow

networks:
  airflow:

volumes:
  postgres-db-volume:
